export let PRODUCT_REQUEST = "PRODUCT_REQUEST";
export let PRODUCT_FAILURE = "PRODUCT_FAILURE";

//POST
export let ADD_PRODUCT_SUCESS = "ADD_PRODUCT_SUCESS";

//GET
export let GET_PRODUCT_SUCESS = "GET_PRODUCT_SUCESS";

//PATCH
export let PATCH_PRODUCT_SUCESS = "PATCH_PRODUCT_SUCESS";
